### ISSUE TITLE
Category icons broken

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis#1874]
Screenshot:
![grafik](https://user-images.githubusercontent.com/18488086/53684536-ec9c1800-3d0e-11e9-9dc5-085b2264929f.png)

## Most likely reason:
After the script ids have changed, the generated css looks like this:
```css
#applications.accessoriesButton{
-fx-background-image: url('file:~/.Phoenicis/cache/git-331995911/Applications/Accessories/icon.png');
}
```

Correct would be most likely:
```css
#accessoriesButton{
-fx-background-image: url('file:~/.Phoenicis/cache/git-331995911/Applications/Accessories/icon.png');
}
```
