### ISSUE TITLE
provide snap

### ISSUE THREAD

**Issue by Ads20000** [PhoenicisOrg/phoenicis#752]
I haven't attempted this with anything Wine (or even anything Java) so far, so this may prove very difficult, but would be nice if packaging Phoenicis as a [Snap](https://snapcraft.io/) was on the to-do list.

(See [this](https://tutorials.ubuntu.com/tutorial/create-first-snap#0) for how to create Snaps)

I'll definitely have time to give this a go after 8th June.

Edit: well that didn't happen. In any case, I haven't successfully snapped an app yet at all because I'm not a developer and so I'm rather naive :/

**Comment by plata** [comment]
I guess we need: https://snapcraft.io/docs/reference/plugins/maven

**Comment by plata** [comment]
So the yaml needs to look somewhat like this:
```yaml
name: phoenicis
version: 'beta'
summary: Phoenicis Snap
description: |
  Some description here.

grade: devel
confinement: devmode

parts:
  phoenicis:
    plugin: maven
    source: https://github.com/PlayOnLinux/POL-POM-5.git
```

**Comment by plata** [comment]
Building this gives me: `package javafx.event does not exist` and similar.

**Comment by plata** [comment]
It works with:
```yaml
parts:
  phoenicis:
    plugin: maven
    source: https://github.com/PlayOnLinux/POL-POM-5.git
    build: |
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
        mvn clean package
```
But I think it should be possible without setting the environment somehow?

**Comment by plata** [comment]
With installation:
```yaml
name: phoenicis-snap
version: 'beta'
summary: Phoenicis Snap
description: |
  Some description here.

grade: devel
confinement: devmode

apps:
  phoenicis-javafx-snap:
    command: usr/bin/phoenicis-javafx
    plugs: [home]

parts:
  phoenicis:
    plugin: maven
    source: https://github.com/PlayOnLinux/POL-POM-5.git
    build: |
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
        mvn clean package
    install: |
      cd phoenicis-dist/target
      unzip phoenicis-dist
      cd phoenicis-dist
      mv phoenicis-javafx $SNAPCRAFT_PART_INSTALL/usr/bin/phoenicis-javafx
      mv lib $SNAPCRAFT_PART_INSTALL/usr/bin/lib
```

**Comment by madoar** [comment]
This is quite dangerous in my eyes, what happens if the user uses oraclejdk instead of openjdk?

**Comment by Ads20000** [comment]
@plata does this plugin not fetch its own Java to use inside the Snap as it were? If it uses the Java currently installed or effectively overrides the existing Java installation globally this is a bad idea.

**Comment by Ads20000** [comment]
You could bundle Java in the package maybe? Though that would increase the size of the package a lot! And I'm not sure how to go about doing this anyway. It may be that we should make a common Java platform Snap for other Snaps to use to bring down size, though this would be hard work! Ask on the [Snapcraft forums](https://forum.snapcraft.io/) if you need to :)

**Comment by plata** [comment]
@madoar I know. I'm not even sure why we need this environment. It should be possible to build without it, right?

**Comment by madoar** [comment]
@plata take a look here: https://github.com/dataart-telco/mwc-snaps/blob/d892247d5bb0dc31d11e1bbfd74e31c3c263e3d2/camera-app-snap/snapcraft.yaml

It seems like you can specify `stage-packages` which seem to be needed dependencies.

I've never used Snap myself, so I can't give you much help for this.

**Comment by plata** [comment]
It's possible to replace the manual build with:
```yaml
stage-packages: [openjdk-8-jre, openjfx]
```
But then I get: `Could not find any built jar files for part`.

Also looked into snap for the first time yesterday ;)

**Comment by madoar** [comment]
Where did you put this yaml file? 
I'm not sure how it should find the path to the jar in the correct project.

**Comment by plata** [comment]
I don't even know if we can use the jar directly because we need the `lib` folder etc. (is this really the way you should deliver Java applications normally?)

**Comment by madoar** [comment]
I don't know.
When I release a Java application, I would normally create a single jar file, that contains all needed libraries, especially if these libraries are jar files too.
Therefore it's quite simple for me to distribute my applications.

**Comment by plata** [comment]
@qparis can you explain why we have this structure with several jar's in `lib`?

**Comment by madoar** [comment]
I think the reason is, that we've essentially two POL 5 applications that are distributed together:

- The CLI
- The JavaFX GUI Client

To save some space, it's therefore better to ship the libs in a separate folder once, that to pack them in each needed jar file (one for the cli and one for the javafx application).

**Comment by plata** [comment]
Makes sense. I know use the combination:
```yaml
stage-packages: [openjdk-8-jre, openjfx]
build: |
  mvn clean package
```
Builds and installs but gives `Error: Could not find or load main class org.phoenicis.javafx.JavaFXApplication` when I try to run it.

**Comment by madoar** [comment]
I guess it's still missing the part where you specify the jar you associate with the snap application.

I must say that the documentation for the maven plugin is quite.... short.

**Comment by qparis** [comment]
We can easily create a standalone package with the maven assembly plugin if necessary, if required. I think it could be a good idea in our case. 

We just have to add this piece of code in phoenicis-javafx app 

<build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.phoenicis.javafx.JavaFXApplication</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by Ads20000** [comment]
@madoar 'I must say that the snap documentation for the maven plugin is quite.... short.' I'll flag that up with the Snapcraft guys thanks!

**Comment by plata** [comment]
@qparis I cannot get that working somehow. Doesn't seem to create any output.

**Comment by madoar** [comment]
@plata try the following:
```xml
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.phoenicis.javafx.JavaFXApplication</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id> <!-- this is used for inheritance merges -->
                        <phase>package</phase> <!-- bind to the packaging phase -->
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
The problem is that the plugin wasn't bound to the package phase.

**Comment by plata** [comment]
That works. But when I try to run, I get: `main class org.phoenicis.javafx.JavaFXApplication could not be loaded`.

**Comment by madoar** [comment]
How do you run it?

**Comment by plata** [comment]
`java -jar phoenicis-javafx-5.0-SNAPSHOT-jar-with-dependencies.jar `

**Comment by madoar** [comment]
If I add the given snapshot to the `pom.xml` file in the `phoenicis-javafx` project and afterwards run your command in the target folder of the `phoenicis-javafx` project it works for me.

**Comment by plata** [comment]
Strange.

**Comment by plata** [comment]
I can't even run it via `phoenicis.sh` in dist anymore. However, it works fine from my IDE.

**Comment by madoar** [comment]
What java version are you using? If I remember correctly you're using OpenJDK right?
I'm using OracleJDK, maybe that's the reason?
```bash
marc@marc-desktop ~ $ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by plata** [comment]
I found that I had JRE 9 installed as well. Maybe that's the problem.

**Comment by plata** [comment]
After deleting JRE 9 and fixing a dangling alternative (as described [here](https://askubuntu.com/questions/110423/java-command-not-found)), I can run it again.

**Comment by plata** [comment]
With the following yaml, it begins to start:
```yaml
name: phoenicis-snap
version: 'beta'
summary: Phoenicis Snap
description: |
  Some description here.

grade: devel
confinement: devmode

apps:
  javafx:
    command: usr/bin/phoenicis.sh
    plugs: [home]

parts:
  phoenicis:
    plugin: maven
    source: https://github.com/PlayOnLinux/POL-POM-5.git
    stage-packages: [openjdk-8-jre, openjfx]
    build: |
       mvn clean package
    install: |
      cd phoenicis-dist/target
      unzip phoenicis-dist
      cd phoenicis-dist
      sed -i s:$POL_HOME/lib/:$POL_HOME/../lib/phoenicis/:g phoenicis.sh
      cp phoenicis.sh $SNAPCRAFT_PART_INSTALL/usr/bin
      cp -r lib $SNAPCRAFT_PART_INSTALL/usr/lib/phoenicis
```

But fails immediately with:
```
Error: JavaFX detected no fonts! Please refer to release notes for proper font configuration
```

**Comment by plata** [comment]
This error can be fixed with
```yaml
stage-packages: [openjdk-8-jre, openjfx, fonts-freefont-ttf]
```

**Comment by plata** [comment]
Not sure if the fonts need to be configured like [here](https://github.com/ubuntu/snappy-playpen/blob/af7154cc9cac61d55b17c4aa9517c4d7c003a1a0/openjdk-demo/FileChooserDemo.sh).

**Comment by madoar** [comment]
Does it work correctly if you add the fonts to the `stage-packages`?

**Comment by plata** [comment]
How?

**Comment by madoar** [comment]
It seems like I've misread your last post.

**Comment by Ads20000** [comment]
A desktop helper might help with the fonts issue. See [here](https://wiki.ubuntu.com/snapcraft/parts) (<kbd>Ctrl</kbd>+<kbd>F</kbd> for 'desktop)

**Comment by plata** [comment]
Can you try it?

**Comment by Ads20000** [comment]
What's the command you're using to run the snap? :)

**Comment by Ads20000** [comment]
There's some work going on for the fonts issue [here](https://forum.snapcraft.io/t/desktop-allow-access-to-host-system-fonts/1796/2)

**Comment by plata** [comment]
Check this for how to use snaps: <https://snapcraft.io/docs/core/usage>
In our case, the snap is called "phoenicis-snap".

**Comment by Ads20000** [comment]
```
$ phoenicis-snap
phoenicis-snap: command not found
$ phoenicis-snap.phoenicis
phoenicis-snap.phoenicis: command not found
$ phoenicis-snap.phoenicis.sh
phoenicis-snap.phoenicis.sh: command not found
```

**Comment by Ads20000** [comment]
Oh wait, is this the right command (you called the app `javafx`)?

```
$ snap run phoenicis-snap.javafxlibGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error:  BadValue
  Request Major code 155 (GLX)
  Request Minor code 24 ()
  Value 0x0
  Error Serial #39
  Current Serial #40
```

**Comment by plata** [comment]
Yes. We have will javafx and cli.

**Comment by Ads20000** [comment]
Got it.

The error I get now:
```
$ snap run phoenicis-snap.javafx
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error:  BadValue
  Request Major code 155 (GLX)
  Request Minor code 24 ()
  Value 0x0
  Error Serial #39
  Current Serial #40
```

My `snapcraft.yaml`
```
name: phoenicis-snap
version: 'beta'
summary: Phoenicis Snap
description: |
  Some description here.

grade: devel
confinement: devmode

apps:
  javafx:
    command: usr/bin/phoenicis.sh
    plugs:
      - home

parts:
  phoenicis:
    plugin: maven
    source: https://github.com/PlayOnLinux/POL-POM-5.git
    stage-packages:
      - openjdk-8-jre
      - openjfx
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libgles2-mesa
    build: |
       mvn clean package
    install: |
      cd phoenicis-dist/target
      unzip phoenicis-dist
      cd phoenicis-dist
      sed -i s:$POL_HOME/lib/:$POL_HOME/../lib/phoenicis/:g phoenicis.sh
      cp phoenicis.sh $SNAPCRAFT_PART_INSTALL/usr/bin
      cp -r lib $SNAPCRAFT_PART_INSTALL/usr/lib/phoenicis
    after:
      - desktop-glib-only
```
I think I've added the right dependencies to fix the error...hmm
